"""Rebuild the original English sample pack. Runtime reads only the generated JSON."""
import json
from pathlib import Path
Q=[]
def base(kind,topic,prompt,explanation,rfc):
    return dict(id=f'{kind}-{sum(q["type"]==kind for q in Q)+1:02d}',type=kind,topic=topic,prompt=prompt,explanation=explanation,source=f'https://www.rfc-editor.org/rfc/rfc{rfc}.html')
def tf(topic,prompt,answer,explanation,rfc):
    Q.append(dict(base('true_false',topic,prompt,explanation,rfc),answer=answer))
def mc(topic,prompt,choices,correct,explanation,rfc):
    Q.append(dict(base('multiple_choice',topic,prompt,explanation,rfc),choices=[dict(id=chr(97+i),text=s) for i,s in enumerate(choices)],answer=chr(97+correct)))
def sa(topic,prompt,answers,explanation,rfc):
    Q.append(dict(base('short_answer',topic,prompt,explanation,rfc),answers=answers))
def oe(topic,prompt,answer,concepts,explanation,rfc):
    Q.append(dict(base('open_ended',topic,prompt,explanation,rfc),modelAnswer=answer,concepts=concepts))
tf('TCP','TCP provides an ordered byte stream.',True,'TCP presents bytes to the application in sequence.',9293)
tf('UDP','UDP guarantees that every datagram arrives.',False,'Applications must handle loss when using UDP.',768)
tf('IPv4','An IPv4 address contains 32 bits.',True,'IPv4 addresses have four 8-bit octets.',791)
tf('IPv6','An IPv6 address contains 64 bits.',False,'An IPv6 address is 128 bits long.',8200)
tf('DNS','DNS can cache answers to reduce repeated lookups.',True,'Cached records remain usable according to their TTL.',1034)
tf('HTTP','An HTTP 404 response indicates a successful request.',False,'404 means the requested resource was not found.',9110)
tf('ARP','ARP can resolve an IPv4 address to an Ethernet address on a local link.',True,'ARP discovers the link-layer address of an IPv4 neighbor.',826)
tf('Subnetting','A /24 IPv4 prefix leaves 8 bits outside the network prefix.',True,'32 minus 24 leaves 8 host bits.',4632)
tf('TCP','TCP sequence numbers normally count bytes, not packets.',True,'The sequence space tracks stream bytes; SYN and FIN also consume sequence space.',9293)
tf('UDP','The UDP header is 8 bytes long.',True,'Four 16-bit fields make an 8-byte header.',768)
tf('Routing','OSPF is a link-state routing protocol.',True,'OSPF routers exchange link-state information.',2328)
tf('Routing','BGP is primarily used to exchange routes between autonomous systems.',True,'BGP supports inter-domain routing and policy.',4271)
tf('IPv4','IPv4 TTL increases at each router hop.',False,'Forwarding routers decrease TTL, preventing indefinite circulation.',791)
tf('HTTP','HTTP GET is intended to retrieve a representation of a resource.',True,'GET requests transfer of a selected representation.',9110)
tf('DNS','A DNS MX record identifies a mail exchanger for a domain.',True,'MX records describe mail delivery destinations.',1035)
tf('DHCP','DHCP can automatically assign an IPv4 address to a host.',True,'DHCP offers address leases and other configuration.',2131)
tf('TCP','TCP flow control and congestion control protect exactly the same resource.',False,'Flow control protects the receiver; congestion control responds to network capacity.',5681)
tf('Ethernet','The standard Ethernet MTU for an IP datagram is 1500 bytes.',True,'This limit concerns the IP datagram, excluding the Ethernet header.',894)
tf('IPv6','IPv6 routers fragment packets while forwarding them.',False,'IPv6 fragmentation is performed by the source, not intermediate routers.',8200)
tf('Subnetting','An IPv4 /26 block contains 64 total addresses.',True,'Six host bits allow 2^6 addresses.',4632)
mc('Layers','Which layer provides process-to-process communication?', ['Link','Transport','Physical','Internet'],1,'Transport protocols use ports to distinguish application endpoints.',1122)
mc('TCP','Which sequence establishes a typical TCP connection?', ['ACK → SYN → FIN','FIN → ACK → SYN','SYN → SYN-ACK → ACK','SYN → FIN → ACK'],2,'The three-way handshake synchronizes sequence numbers.',9293)
mc('DNS','Which DNS record type maps a name to an IPv4 address?', ['MX','AAAA','CNAME','A'],3,'An A record carries an IPv4 address.',1035)
mc('Subnetting','What subnet mask corresponds to /26?', ['255.255.255.0','255.255.255.192','255.255.255.224','255.255.255.128'],1,'The final octet has two prefix bits: 11000000.',4632)
mc('HTTP','Which response code normally means Not Found?', ['200','301','404','500'],2,'404 reports that a current representation was not found.',9110)
mc('UDP','Which application requirement most directly favors TCP over UDP?', ['Reliable ordered delivery','No transport connection setup','Independent datagrams','Minimal transport header'],0,'TCP supplies reliable ordered delivery as part of the transport.',9293)
mc('Routing','Which algorithm is used to compute OSPF shortest paths?', ['Binary search','Bellman-Ford only','Dijkstra','Round-robin'],2,'OSPF builds a shortest-path tree from its link-state database.',2328)
mc('IPv4','Which IPv4 field limits the lifetime of a packet?', ['IHL','TTL','Source port','Window'],1,'TTL is reduced during forwarding.',791)
mc('DHCP','What is the usual initial DHCP exchange?', ['Offer → Discover → ACK → Request','Request → ACK → Discover → Offer','Discover → Offer → Request → ACK','ACK → Request → Offer → Discover'],2,'A client discovers servers, accepts an offer, and receives acknowledgment.',2131)
mc('DNS','Which DNS record represents an alias?', ['A','MX','NS','CNAME'],3,'CNAME identifies a canonical name for an alias.',1034)
mc('ARP','What does an ARP request on Ethernet normally use as its destination?', ['The local broadcast address','The remote web server MAC','The DNS server IP','A TCP port'],0,'The request reaches local nodes so the address owner can reply.',826)
mc('TCP','What does the TCP receive window primarily support?', ['Routing','Name resolution','Flow control','Ethernet switching'],2,'The advertised window limits data according to receiver capacity.',9293)
mc('Subnetting','What is the network address of 192.168.1.77/26?', ['192.168.1.0','192.168.1.64','192.168.1.77','192.168.1.128'],1,'/26 boundaries occur every 64 addresses in the last octet.',4632)
mc('IPv6','How long is an IPv6 address?', ['32 bits','48 bits','64 bits','128 bits'],3,'IPv6 expands the address size to 128 bits.',8200)
mc('HTTP','Which HTTP method requests headers without the response content of GET?', ['POST','HEAD','PUT','CONNECT'],1,'HEAD has GET-like semantics but no response content.',9110)
mc('Routing','Which BGP attribute lists autonomous systems along a route?', ['AS_PATH','TTL','MAC_PATH','TCP_WINDOW'],0,'AS_PATH records AS traversal information.',4271)
mc('UDP','Which field is absent from the UDP header?', ['Source port','Length','Sequence number','Checksum'],2,'UDP does not include TCP-style sequence numbering.',768)
mc('TCP','Which mechanism detects missing acknowledgments and triggers retransmission?', ['ARP cache','Retransmission timer','DNS TTL','Subnet mask'],1,'TCP retransmits when its retransmission timer expires.',6298)
mc('Ethernet','Which EtherType identifies IPv4?', ['0x86DD','0x0806','0x0800','0x8100'],2,'IPv4 over Ethernet uses EtherType 0x0800.',894)
mc('Subnetting','How many conventional usable host addresses are in an IPv4 /27 subnet?', ['32','30','64','62'],1,'There are 32 total addresses; the network and broadcast addresses leave 30.',4632)
sa('TCP','What does TCP stand for?', ['Transmission Control Protocol'], 'TCP is the Transmission Control Protocol.',9293)
sa('UDP','What does UDP stand for?', ['User Datagram Protocol'], 'UDP is the User Datagram Protocol.',768)
sa('DNS','What does DNS stand for?', ['Domain Name System'], 'DNS is the Domain Name System.',1034)
sa('IPv4','How many bits are in an IPv4 address? Enter a number.', ['32','32 bits'], 'Four octets contain 32 bits.',791)
sa('IPv6','How many bits are in an IPv6 address? Enter a number.', ['128','128 bits'], 'IPv6 uses 128-bit addresses.',8200)
sa('Subnetting','How many total addresses are in an IPv4 /24 block?', ['256','256 addresses'], '2^(32−24) equals 256.',4632)
sa('Subnetting','Write the dotted-decimal subnet mask for /24.', ['255.255.255.0'], 'The first 24 bits are set.',4632)
sa('Subnetting','What is the network address of 10.0.0.37/24?', ['10.0.0.0','10.0.0.0/24'], 'Zeroing the 8 host bits gives 10.0.0.0.',4632)
sa('DNS','Which DNS record type stores a mail exchanger? Give the abbreviation.', ['MX'], 'MX records identify mail exchangers.',1035)
sa('ARP','Which protocol resolves an IPv4 neighbor to its Ethernet address?', ['ARP','Address Resolution Protocol'], 'ARP obtains a local link-layer address.',826)
sa('HTTP','Which HTTP status code means Not Found?', ['404','404 Not Found'], '404 is the Not Found status.',9110)
sa('TCP','Which TCP flag initiates a typical connection?', ['SYN','synchronize'], 'SYN initiates sequence-number synchronization.',9293)
sa('TCP','Which TCP flag indicates that the sender has no more data to send?', ['FIN','finish'], 'FIN closes one direction of the byte stream.',9293)
sa('UDP','How many bytes are in the UDP header?', ['8','8 bytes'], 'The UDP header has four 2-byte fields.',768)
sa('IPv4','Which IPv4 field prevents packets from circulating indefinitely? Give its abbreviation.', ['TTL','Time To Live','Time-to-live'], 'Routers decrease TTL during forwarding.',791)
sa('DHCP','Which protocol dynamically leases IPv4 addresses to hosts?', ['DHCP','Dynamic Host Configuration Protocol'], 'DHCP distributes leased addresses and configuration.',2131)
sa('Routing','Which routing protocol uses an AS_PATH attribute?', ['BGP','Border Gateway Protocol'], 'BGP carries AS-path information for inter-domain routing.',4271)
sa('Routing','Which shortest-path algorithm does OSPF use?', ['Dijkstra','Dijkstra algorithm',"Dijkstra's algorithm",'Dijkstra’s algorithm'], 'OSPF computes a shortest-path tree.',2328)
sa('Ethernet','What is the standard Ethernet MTU for IP, in bytes?', ['1500','1500 bytes','1,500'], 'An IP datagram normally fits in 1500 Ethernet payload bytes.',894)
sa('Subnetting','How many conventional usable host addresses are in an IPv4 /26 subnet?', ['62','62 hosts','62 addresses'], '64 total addresses minus network and broadcast leaves 62.',4632)
oe('TCP vs UDP','Contrast TCP and UDP in terms of delivery guarantees. Write 1–2 sentences.', 'TCP provides reliable, ordered delivery. UDP does not guarantee delivery or ordering.', [['TCP','Transmission Control Protocol'],['reliable','reliability'],['ordered','ordering','in order'],['UDP','User Datagram Protocol'],['not guarantee','does not guarantee','no guarantee','unreliable','best effort']], 'TCP tracks a byte stream; UDP offers independent datagrams.',768)
oe('TCP','How does TCP recover from a lost segment? Mention acknowledgments and retransmission.', 'TCP uses acknowledgments to track received data and retransmits missing data after a timeout or loss detection.', [['acknowledgments','acknowledgements','ACK','ACKs'],['retransmit','retransmits','retransmission','resend','resends']], 'Missing acknowledgments can cause retransmission.',9293)
oe('Flow control','What is the purpose of TCP flow control, and which window supports it?', 'Flow control protects the receiver from being overwhelmed by using the receive window.', [['receiver','receiving host','receiving endpoint'],['receive window','receiver window','advertised window','rwnd']], 'The receiver advertises how much more data it can accept.',9293)
oe('Congestion control','What does congestion control protect, and what happens to the sending rate when congestion is detected?', 'Congestion control protects the network by reducing the sending rate when congestion is detected.', [['network','routers','router'],['reduce','reduces','reducing','decrease','decreases','decreasing','lower','lowers']], 'A congestion signal leads the sender to back off.',5681)
oe('DNS','Why does DNS caching help? Mention repeated queries and latency.', 'Caching avoids repeated DNS queries and reduces lookup latency.', [['queries','query','lookups','lookup'],['latency','delay','response time'],['reduce','reduces','avoid','avoids','fewer','lower']], 'Cached answers can avoid another DNS exchange until expiration.',1034)
oe('DNS','What is the role of an authoritative DNS server?', 'An authoritative DNS server provides authoritative records for its zone.', [['records','record','answers','answer'],['zone','zones']], 'Authority belongs to the server responsible for the zone data.',1034)
oe('Subnetting','What does an IPv4 /24 prefix say about network bits and host bits?', 'It reserves 24 bits for the network prefix and leaves 8 host bits.', [['24'],['network','prefix'],['8'],['host','hosts']], 'IPv4 has 32 bits in total.',4632)
oe('ARP','Explain why a host uses ARP before sending an IPv4 packet to a local Ethernet neighbor.', 'ARP maps the neighbor’s IPv4 address to a MAC address for local Ethernet delivery.', [['IPv4','IP address','IP addresses'],['MAC','Ethernet address','hardware address'],['local','neighbor','neighbour','link']], 'The Ethernet frame needs a local destination hardware address.',826)
oe('HTTP','Explain the difference between HTTP GET and POST at a high level.', 'GET retrieves a representation, while POST asks a resource to process the supplied content.', [['GET'],['retrieve','retrieves','retrieving','fetch','fetches','read'],['POST'],['process','processes','processing']], 'POST semantics depend on the target resource.',9110)
oe('HTTP','What does an HTTP 301 response indicate?', 'It indicates that the resource has moved permanently to a different URI.', [['permanent','permanently'],['moved','redirect','redirection','redirected'],['URI','URL','location','address']], '301 is a permanent redirect status.',9110)
oe('IPv4','Why is TTL important when a routing loop occurs?', 'Routers decrement TTL until it reaches zero, then discard the packet so it cannot loop forever.', [['TTL','time to live'],['zero','0'],['discard','discarded','drop','dropped']], 'TTL bounds the packet lifetime.',791)
oe('Routing','Explain the purpose of a default route.', 'A default route is used when no more specific route matches the destination.', [['default'],['no more specific','no specific','no other','otherwise','unmatched']], 'The least-specific prefix is the fallback match.',4632)
oe('Routing','How does OSPF use link-state information?', 'OSPF builds a topology database and computes shortest paths with Dijkstra’s algorithm.', [['topology','database','graph'],['Dijkstra'],['shortest path','shortest paths','shortest path tree']], 'A shared topology view enables shortest-path calculation.',2328)
oe('Routing','How can BGP use AS_PATH to detect a loop?', 'A BGP router checks whether its own AS appears in the AS_PATH and rejects the looping route.', [['own AS','own autonomous system','local AS'],['AS_PATH','AS path'],['reject','rejects','discard','discards','ignore','ignores']], 'An AS normally rejects routes containing itself in the path.',4271)
oe('DHCP','Describe the four-message exchange used to obtain an initial DHCP lease.', 'The client sends Discover, the server sends Offer, the client sends Request, and the server sends ACK.', [['Discover','DHCPDISCOVER'],['Offer','DHCPOFFER'],['Request','DHCPREQUEST'],['ACK','DHCPACK','acknowledgment','acknowledgement']], 'The usual exchange is often called DORA.',2131)
oe('TCP','Why does TCP use a three-way handshake?', 'The handshake synchronizes sequence numbers and establishes a connection between both endpoints.', [['sequence number','sequence numbers'],['synchronize','synchronizes','synchronization','sync','agree'],['connection','endpoints']], 'Each endpoint communicates its initial sequence number.',9293)
oe('UDP','Why might a real-time application choose UDP and handle loss itself?', 'UDP avoids a connection handshake and transport retransmission delays, which can help latency-sensitive applications.', [['UDP'],['handshake','connection setup'],['latency','delay','delays']], 'The application can choose how to react to missing datagrams.',768)
oe('IPv6','Who performs fragmentation in IPv6, and do routers fragment packets?', 'Only the source performs IPv6 fragmentation; routers do not fragment packets.', [['source','sender','sending host'],['routers','router'],['do not','does not','never','cannot','not fragment']], 'An IPv6 source may use a Fragment header.',8200)
oe('Ethernet','Why does IP encapsulation over Ethernet need both IP and MAC addresses?', 'IP addresses support delivery across networks, while MAC addresses identify endpoints on the local Ethernet link.', [['IP'],['networks','network','routing'],['MAC'],['local','link']], 'An IP datagram is carried inside an Ethernet frame.',894)
oe('Subnetting','How do you calculate the number of total addresses in an IPv4 /n block?', 'There are 32 minus n host bits, so the total is 2 raised to the power of 32 minus n.', [['32'],['n'],['2'],['host','power','raised','exponent']], 'Total block size includes reserved addresses where applicable.',4632)
assert len(Q)==80
out=Path(__file__).resolve().parents[1]/'public/data/questions.en.json'
out.write_text(json.dumps(dict(version=1,title='Computer Networks · Exam Essentials',questions=Q),ensure_ascii=False,indent=2)+'\n')
print(f'Wrote {len(Q)} questions to {out}')
